# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Better Specs. Testing Guidelines for Developers."
email: "bettterspecs@lelylan.com"
description: > # this means to ignore newlines until "baseurl:"
  Better Specs is a collection of best practices developers 
  learned while testing apps that you can use to improve your coding 
  skills, or simply for inspiration.
url: "https://alpha.betterspecs.org" # the base hostname & protocol for your site
twitter_username: betterspecs
github_username:  lelylan

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
